### ISSUE TITLE
Make `id` values consistant

### ISSUE THREAD

**Issue by sanders41** [sanders41/meilisearch-tui#28]
Currently there is a mix of `snake_case` and `kebab-case` names used for `id`s. The Textual preferred way to name these seems to be kebab case so all the snake case ids should be changed to kebab case.

One example of this can be found [here](https://github.com/sanders41/meilisearch-tui/blob/4e31f6ea843ceccb63ba7c24b839cdc0a94f1f33/meilisearch_tui/__main__.py#L42) where `generic_error` should be renamed to `generic-error`. All queries and classes referencing these ids should be updated as well.

**Comment by tymnec** [comment]
Assign this to me.
