### ISSUE TITLE
Add hybrid/semantic searches across vectors

### ISSUE THREAD

**Issue by doreilly257** [sanders41/meilisearch-tui#371]
Is it possible to provide the option to do semantic vector searches across indexes.

curl -X POST -H 'content-type: application/json' \
  'localhost:7700/indexes/products/search' \
  --data-binary '{ 
    "q": "kitchen utensils",
    **"hybrid": {**
      **"semanticRatio": 0.9,**
      **"embedder": "default"**
    }
  }'

**Comment by sanders41** [comment]
Currently it isn't possible. It should be relatively easy to add, the only problem is with semantic search being experimental I don't want to make it the default. What I'm thinking is there could be a command line flag when starting the TUI that enables hybrid search.

Is this something you would like to work on? If so feel free to ask questions as you go. If not I will take a look at adding it.

**Comment by doreilly257** [comment]
Happy to work on it, will create a branch soon, agreed will do as an argument for anything experimental, will base on Meilisearch 1.7.0 rcs, as some settings and formats have changed since 1.3/1.6.

**Comment by doreilly257** [comment]
Have sent a merge and PR, sorry be nice first time for me :) if wrong
please let me know if the code needs work, or the process or whatever. I am
working on a mac so the justfile was not working.

Thanks,

Dan

**Comment by sanders41** [comment]
Don't worry, we'll go through it together and I can get you through anywhere you get stuck 😀

`just` isn't required, but will make things easier. Assuming you are using homebrew you can install it on Mac with `brew install just`
