### ISSUE TITLE
Switch tab color

### ISSUE THREAD

**Issue by sanders41** [sanders41/meilisearch-tui#65]
The default blue is being used now, should switch it to one of the theme colors. I am thinking `$secondary`.

**Comment by bilalakhter** [comment]
u mean replace all primary color with secondary for background and for text replace secondary with primary? what about lighten and darken color

**Comment by tymnec** [comment]
Hey, @sanders41 you can assign it to me!. I would like to work on this one.

**Comment by sanders41** [comment]
Hi @tymnec, just checking in to see if you still plan on working on this.

**Comment by tymnec** [comment]
Actually, I was busy in my some other work. I will do this soon in a day or two.
